# Generated by Django 3.1.7 on 2021-07-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_auto_20210714_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
    ]
