# Generated by Django 3.1.7 on 2021-07-31 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210731_1452'),
        ('child', '0003_auto_20210718_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': '아이들', 'verbose_name_plural': '아이들'},
        ),
        migrations.AlterField(
            model_name='child',
            name='child_name',
            field=models.CharField(max_length=5, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.CharField(max_length=5, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='room',
            field=models.CharField(max_length=5, verbose_name='반'),
        ),
        migrations.AlterField(
            model_name='child',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='작성자'),
        ),
    ]
